// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Software_Engineering_2025.Data;

#nullable disable

namespace Software_Engineering.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Software_Engineering_2025.Models.Admin", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("Admin_Level")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("Last_Login")
                        .HasColumnType("datetime2");

                    b.HasKey("User_ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Carer", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("Availability_Schedule")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("User_ID");

                    b.ToTable("Carers");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.CarerAccess", b =>
                {
                    b.Property<int>("Access_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Access_ID"));

                    b.Property<int?>("CarerUser_ID")
                        .HasColumnType("int");

                    b.Property<int>("Carer_User_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Granted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Granted_By_User_ID")
                        .HasColumnType("int");

                    b.Property<int>("Patient_User_ID")
                        .HasColumnType("int");

                    b.Property<string>("Permission_Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Revoked_At")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Revoked_By_User_ID")
                        .HasColumnType("int");

                    b.HasKey("Access_ID");

                    b.HasIndex("CarerUser_ID");

                    b.HasIndex("Carer_User_ID");

                    b.HasIndex("Granted_By_User_ID");

                    b.HasIndex("Patient_User_ID");

                    b.HasIndex("Revoked_By_User_ID");

                    b.ToTable("CarerAccesses");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Clinician", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("License_Number")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialisation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("User_ID");

                    b.ToTable("Clinicians");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Gender", b =>
                {
                    b.Property<int>("Gender_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gender_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Gender_ID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Gender_ID = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Gender_ID = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Gender_ID = 3,
                            Name = "Other"
                        },
                        new
                        {
                            Gender_ID = 4,
                            Name = "Prefer not to say"
                        });
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Patient", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Clinician_User_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Gender_ID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("User_ID");

                    b.HasIndex("Clinician_User_ID");

                    b.HasIndex("Gender_ID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Activation_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Is_Activated")
                        .HasColumnType("bit");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("User_Type_ID")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("User_Type_ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.UserType", b =>
                {
                    b.Property<int>("User_Type_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Type_ID"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("User_Type_ID");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            User_Type_ID = 1,
                            Description = "System Administrator with full access",
                            Type_Name = "Admin"
                        },
                        new
                        {
                            User_Type_ID = 2,
                            Description = "Healthcare professional managing patients",
                            Type_Name = "Clinician"
                        },
                        new
                        {
                            User_Type_ID = 3,
                            Description = "Patient user monitoring pressure data",
                            Type_Name = "Patient"
                        },
                        new
                        {
                            User_Type_ID = 4,
                            Description = "Authorised carer with access to patient data",
                            Type_Name = "Carer"
                        });
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Admin", b =>
                {
                    b.HasOne("Software_Engineering_2025.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Software_Engineering_2025.Models.Admin", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Carer", b =>
                {
                    b.HasOne("Software_Engineering_2025.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Software_Engineering_2025.Models.Carer", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.CarerAccess", b =>
                {
                    b.HasOne("Software_Engineering_2025.Models.Carer", null)
                        .WithMany("CarerAccesses")
                        .HasForeignKey("CarerUser_ID");

                    b.HasOne("Software_Engineering_2025.Models.User", "CarerUser")
                        .WithMany()
                        .HasForeignKey("Carer_User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Software_Engineering_2025.Models.User", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("Granted_By_User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Software_Engineering_2025.Models.User", "PatientUser")
                        .WithMany()
                        .HasForeignKey("Patient_User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Software_Engineering_2025.Models.User", "RevokedByUser")
                        .WithMany()
                        .HasForeignKey("Revoked_By_User_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CarerUser");

                    b.Navigation("GrantedByUser");

                    b.Navigation("PatientUser");

                    b.Navigation("RevokedByUser");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Clinician", b =>
                {
                    b.HasOne("Software_Engineering_2025.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Software_Engineering_2025.Models.Clinician", "User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Patient", b =>
                {
                    b.HasOne("Software_Engineering_2025.Models.Clinician", "Clinician")
                        .WithMany("Patients")
                        .HasForeignKey("Clinician_User_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Software_Engineering_2025.Models.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("Gender_ID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Software_Engineering_2025.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Software_Engineering_2025.Models.Patient", "User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("Gender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.User", b =>
                {
                    b.HasOne("Software_Engineering_2025.Models.UserType", "UserType")
                        .WithMany("Users")
                        .HasForeignKey("User_Type_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Carer", b =>
                {
                    b.Navigation("CarerAccesses");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Clinician", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.Gender", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("Software_Engineering_2025.Models.UserType", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
